/**
 * pwa.ts
 * -----------------------------------------------------------------------
 * Registers the service worker generated by vite-plugin-pwa, using its
 * virtual module so the registration logic matches whatever Workbox
 * config built the worker. This is what lets the app shell itself (not
 * just the IndexedDB data in storage/db.ts) load with no network
 * connection, fulfilling the offline-first requirement in spec section 5.
 * -----------------------------------------------------------------------
 */
import { registerSW } from 'virtual:pwa-register';

export function registerServiceWorker(): void {
  if (import.meta.env.PROD) {
    registerSW({ immediate: true });
  }
}
